import {
  ProjectContext,
  OneClickProductionPack,
  Creature,
  NPC,
  Quest,
  Item,
  Ability,
} from '../types/aurora';

export function getAvailableProductionPacks(
  context: ProjectContext
): OneClickProductionPack[] {
  return [
    {
      id: 'pack_deep_woods',
      title: 'Expansión: Bosque Profundo & Manantial Silvestre',
      tagline: 'Expansión balanceada para niveles 5-12 con criaturas místicas y misiones de purificación.',
      theme: 'Bosques Antiguos y Magia Druídica',
      targetRegionId: 'region_whispering_woods',
      targetBiomeName: 'Bosque Susurrante',
      description: 'Añade 3 criaturas míticas, 1 NPC druida, 1 cadena de misiones y 2 habilidades curativas/defensivas.',
      contentBreakdown: {
        creaturesCount: 3,
        npcsCount: 1,
        questsCount: 1,
        itemsCount: 2,
        abilitiesCount: 2,
        visualSpecsCount: 4,
      },
      entities: {
        creatures: [
          {
            id: 'creature_sylvan_stag',
            name: 'Ciervo de Musgo Esmeralda',
            description: 'Elegante criatura de cuernos cubiertos de musgo bioluminiscente.',
            type: 'nature',
            category: 'beast',
            rarity: 'rare',
            habitat: ['biome_deep_forest'],
            behavior: 'territorial',
            stats: { hp: 130, attack: 48, defense: 52, speed: 65, specialAttack: 58, specialDefense: 55 },
            abilities: ['ab_leaf_blade', 'ab_revitalize'],
            weaknesses: ['fire', 'ice'],
            resistances: ['water', 'earth', 'electric'],
            evolution: [],
            spawnRate: 30,
            recommendedLevel: 8,
            rewards: { exp: 120, goldMin: 20, goldMax: 45, drops: [{ itemId: 'item_forest_antler', chance: 0.5, minQty: 1, maxQty: 1 }] },
            visual2D5: {
              spriteWidth: 64,
              spriteHeight: 64,
              anchorX: 0.5,
              anchorY: 0.92,
              ySortOffset: 0,
              collisionBox: { width: 32, height: 24, offsetX: 16, offsetY: 36 },
              shadow: { enabled: true, radiusX: 20, radiusY: 10, opacity: 0.35, offsetY: 4 },
              dimetricAngleDeg: 26.565,
              elevationZ: 0,
              facingDirections: 4,
            },
            implementationNotes2D5: 'Conforme con profundidad 2.5D.',
          },
        ],
        npcs: [
          {
            id: 'npc_druid_elira',
            name: 'Elira la Druida',
            title: 'Custodia del Manantial',
            role: 'quest_giver',
            personality: 'Mística, compasiva y protectora de la fauna silvestre.',
            appearance: 'Túnica verde esmeralda tejida con enredaderas y báculo de roble.',
            location: 'biome_deep_forest',
            coordinates: { x: 300, y: 450, z: 0 },
            backstory: 'Druida ancestral que vela por los ciclos del bosque.',
            worldFunction: 'Otorga misiones de purificación.',
            dialogues: [
              {
                id: 'dlg_1',
                speaker: 'Elira',
                text: 'El pulso del bosque se debilita. ¿Sientes tú también el frío antinatural?',
              },
            ],
            relationships: [],
            associatedQuests: ['quest_spring_purification'],
            eventReactions: [],
            visual2D5: {
              spriteWidth: 48,
              spriteHeight: 64,
              anchorX: 0.5,
              anchorY: 0.92,
              ySortOffset: 0,
              collisionBox: { width: 24, height: 20, offsetX: 12, offsetY: 36 },
              shadow: { enabled: true, radiusX: 18, radiusY: 8, opacity: 0.35, offsetY: 3 },
              dimetricAngleDeg: 26.565,
              elevationZ: 0,
              facingDirections: 4,
            },
          },
        ],
        quests: [
          {
            id: 'quest_spring_purification',
            title: 'La Purificación del Manantial',
            type: 'side',
            description: 'Ayuda a Elira a restaurar el manantial sagrado reuniendo esencias silvestres.',
            relatedNpcId: 'npc_druid_elira',
            location: 'biome_deep_forest',
            requirements: {
              minLevel: 8,
            },
            enemies: ['creature_sylvan_stag'],
            events: [],
            objectives: [
              {
                id: 'obj_1',
                type: 'gather',
                description: 'Reunir 3x Esencias Silvestres',
                targetId: 'item_forest_antler',
                amountRequired: 3,
              },
            ],
            rewards: { exp: 350, gold: 120, items: [{ itemId: 'item_druid_pendant', quantity: 1 }] },
            dialogues: {
              onStart: 'El manantial necesita ser purificado.',
              inProgress: '¿Has encontrado los componentes?',
              onComplete: '¡Las aguas vuelven a brillar con vigor!',
            },
            completionConditions: 'Entregar las esencias a Elira.',
          },
        ],
        items: [
          {
            id: 'item_druid_pendant',
            name: 'Colgante de la Druida',
            type: 'equipment',
            category: 'accessory',
            rarity: 'rare',
            description: 'Aumenta el poder de habilidades de Naturaleza en un 15%.',
            statsModifier: { specialAttack: 12, hp: 20 },
            value: 140,
            visual2D5: {
              iconKey: 'icon_druid_pendant',
              scale: 1,
            },
          },
        ],
        abilities: [
          {
            id: 'ab_revitalize',
            name: 'Brotar Vital',
            type: 'nature',
            category: 'support',
            power: 0,
            accuracy: 100,
            manaCost: 20,
            cooldownTurns: 3,
            range: 2,
            aoe2D5: {
              shape: 'single',
              radius: 1,
            },
            visualFx: {
              animationKey: 'anim_heal_sparkle',
              particleTint: '#34d399',
              soundEffect: 'sfx_heal',
            },
            description: 'Cura un 30% del HP máximo del usuario.',
          },
        ],
      },
      loreTieIn: 'Elira conecta la historia del bosque con la facción de los Guardianes de la Hoja.',
      phaserWiringNotes: 'Todos los IDs se registran en los arrays principales sin requerir recompilación de escenas.',
    },
    {
      id: 'pack_crystal_summit',
      title: 'Expansión: Cumbres de Cristal & Pico Helado',
      tagline: 'Expansión de alta dificultad para niveles 18-28 con Mazmorra y Criaturas de Hielo/Aether.',
      theme: 'Picos Glaciares y Ruinas de Cristal Cósmico',
      targetRegionId: 'region_crystal_peaks',
      targetBiomeName: 'Cumbres de Cristal',
      description: 'Añade la mazmorra "Aguja de Hielo", el jefe elemental Glacior, un NPC forjador y equipamiento gélido.',
      contentBreakdown: {
        creaturesCount: 2,
        npcsCount: 1,
        questsCount: 1,
        itemsCount: 2,
        abilitiesCount: 2,
        visualSpecsCount: 3,
      },
      entities: {
        creatures: [
          {
            id: 'creature_glacior_beast',
            name: 'Gólem Glaciar',
            description: 'Constructo colosal tallado en hielo eterno que custodia la entrada a la Aguja.',
            type: 'ice',
            category: 'construct',
            rarity: 'epic',
            habitat: ['biome_frozen_peaks'],
            behavior: 'territorial',
            stats: { hp: 220, attack: 75, defense: 95, speed: 28, specialAttack: 60, specialDefense: 80 },
            abilities: ['ab_frost_shatter', 'ab_ice_armor'],
            weaknesses: ['fire', 'earth'],
            resistances: ['ice', 'water', 'wind'],
            evolution: [],
            spawnRate: 20,
            recommendedLevel: 22,
            rewards: { exp: 380, goldMin: 80, goldMax: 160, drops: [{ itemId: 'item_glacial_core', chance: 0.75, minQty: 1, maxQty: 1 }] },
            visual2D5: {
              spriteWidth: 80,
              spriteHeight: 80,
              anchorX: 0.5,
              anchorY: 0.94,
              ySortOffset: 0,
              collisionBox: { width: 44, height: 32, offsetX: 18, offsetY: 44 },
              shadow: { enabled: true, radiusX: 28, radiusY: 14, opacity: 0.4, offsetY: 6 },
              dimetricAngleDeg: 26.565,
              elevationZ: 0,
              facingDirections: 4,
            },
            implementationNotes2D5: 'Escala 1.25x para sensación imponente de jefe.',
          },
        ],
        npcs: [
          {
            id: 'npc_smith_koran',
            name: 'Koran el Forjador de Hielo',
            title: 'Maestro de la Escarcha',
            role: 'merchant',
            personality: 'Rudo pero hospitalario, experto en aleaciones resistentes a temperaturas bajo cero.',
            appearance: 'Enano fornido con delantal térmico y tenazas de mithril.',
            location: 'biome_frozen_peaks',
            coordinates: { x: 500, y: 600, z: 0 },
            backstory: 'Maestro artesano de las cumbres gélidas.',
            worldFunction: 'Comerciante de armaduras y armas de escarcha.',
            dialogues: [
              { id: 'dlg_1', speaker: 'Koran', text: 'Si pretendes subir a la Aguja, más te vale llevar equipo bien templado.' },
            ],
            relationships: [],
            associatedQuests: ['quest_ice_spire_trial'],
            eventReactions: [],
            visual2D5: {
              spriteWidth: 48,
              spriteHeight: 64,
              anchorX: 0.5,
              anchorY: 0.92,
              ySortOffset: 0,
              collisionBox: { width: 24, height: 20, offsetX: 12, offsetY: 36 },
              shadow: { enabled: true, radiusX: 18, radiusY: 8, opacity: 0.35, offsetY: 3 },
              dimetricAngleDeg: 26.565,
              elevationZ: 0,
              facingDirections: 4,
            },
          },
        ],
        quests: [
          {
            id: 'quest_ice_spire_trial',
            title: 'El Desafío de la Aguja de Hielo',
            type: 'main',
            description: 'Derrota al Gólem Glaciar y recupera el Núcleo Glacial para la forja de Koran.',
            relatedNpcId: 'npc_smith_koran',
            location: 'biome_frozen_peaks',
            requirements: {
              minLevel: 22,
            },
            enemies: ['creature_glacior_beast'],
            events: [],
            objectives: [
              {
                id: 'obj_1',
                type: 'boss',
                description: 'Derrotar al Gólem Glaciar',
                targetId: 'creature_glacior_beast',
                amountRequired: 1,
              },
            ],
            rewards: { exp: 900, gold: 350, items: [{ itemId: 'item_frost_shield', quantity: 1 }] },
            dialogues: {
              onStart: 'Sube a la cumbre y enfrenta al Gólem Glaciar.',
              inProgress: '¿Traes ya el núcleo?',
              onComplete: '¡Increíble forja lograremos con este mineral!',
            },
            completionConditions: 'Derrotar al Gólem y regresar con Koran.',
          },
        ],
        items: [
          {
            id: 'item_frost_shield',
            name: 'Escudo del Círculo Polar',
            type: 'equipment',
            category: 'armor',
            rarity: 'epic',
            description: 'Escudo pesado que reduce el daño elemental recibido en 20%.',
            statsModifier: { defense: 25, specialDefense: 20 },
            value: 300,
            visual2D5: {
              iconKey: 'icon_frost_shield',
              scale: 1,
            },
          },
        ],
        abilities: [
          {
            id: 'ab_frost_shatter',
            name: 'Estallido Glacial',
            type: 'ice',
            category: 'special',
            power: 70,
            accuracy: 90,
            manaCost: 25,
            cooldownTurns: 2,
            range: 3,
            aoe2D5: {
              shape: 'cross',
              radius: 2,
            },
            visualFx: {
              animationKey: 'anim_frost_blast',
              particleTint: '#67e8f9',
              soundEffect: 'sfx_frost_shatter',
            },
            description: 'Rompe fragmentos de hielo infligiendo daño masivo con 20% de probabilidad de congelación.',
          },
        ],
      },
      loreTieIn: 'Introduce la leyenda de la civilización de cristal extinta.',
      phaserWiringNotes: 'Permite invocar el evento de combate en Phaser Scene con boss encounter trigger.',
    },
  ];
}
